name: Syncs master branch -> master-br branch

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Specify node version
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Push changes to sync-branch
        run: |
          git checkout -b master-br || git checkout master-br
          git merge --ff-only master
          git push origin master-br
