name: Syncs master branch -> master-br branch

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Specify node version
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Open pull request
        id: pull
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{github.token}}
          FROM_BRANCH: "master"
          TO_BRANCH: "master-br"
